FROM srlynch1/terraform-ai-tools:latest

RUN npm install -g @github/copilot@v0.0.400-0 && \
    npm cache clean --force


# Add yolo aliases for unattended mode
RUN echo 'alias copiloty="copilot --yolo --disable-builtin-mcps"' >> /home/node/.zshrc && \
    chown node:node /home/node/.zshrc